<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rESPOND_Roles" nsURI="http://www.example.org/rESPOND_Roles"
    nsPrefix="rESPOND_Roles">
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="../../RESPOND_Base/model/RESPOND_Base.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualResponsibilities"
        upperBound="-1" eType="ecore:EClass ../../RESPOND_Context/model/respond_context.ecore#//virtual/VirtualRespondNode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="physicalResponsibilities"
        upperBound="-1" eType="ecore:EClass ../../RESPOND_Context/model/respond_context.ecore#//real/RealRespondNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="../../RESPOND_Base/model/RESPOND_Base.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRoles" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleList" eSuperTypes="../../RESPOND_Base/model/RESPOND_Base.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonList" eSuperTypes="../../RESPOND_Base/model/RESPOND_Base.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
