<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rESPOND_Correspondence" nsURI="http://www.respont-iot.de/rESPOND_Correspondence"
    nsPrefix="rESPOND_Correspondence">
  <eClassifiers xsi:type="ecore:EClass" name="ActivityToContextCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="respondnode" eType="#//RespondNode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitytocontextcorrespondence"
        upperBound="-1" eType="#//ActivityToContextCorrespondence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failingactivitytohealingprocess"
        upperBound="-1" eType="#//FailingActivityToHealingProcess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RespondNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FailingActivityToHealingProcess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failingactivity" lowerBound="1"
        eType="#//FailingTask" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="healingprocess" upperBound="-1"
        eType="#//HealingProcess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailingTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="HealingProcess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drawback" upperBound="-1"
        eType="#//Drawback" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drawback" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Performance" eSuperTypes="#//Drawback"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reliability" eSuperTypes="#//Drawback"/>
  <eClassifiers xsi:type="ecore:EClass" name="Security" eSuperTypes="#//Drawback"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelfHealingService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondences" upperBound="-1"
        eType="#//Correspondence" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
